"""blackjack_tables

Revision ID: 3625e95e1d19
Revises: 990ff82f732d
Create Date: 2022-09-20 14:27:46.514967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3625e95e1d19'
down_revision = '990ff82f732d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'chats',
        sa.Column('tg_chat_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('tg_chat_id'),
    )
    op.create_table(
        'players',
        sa.Column('tg_user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('balance', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('tg_user_id'),
    )
    op.create_table(
        'games',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tg_chat_id', sa.Integer(), nullable=False),
        sa.Column(
            'start_time',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['tg_chat_id'],
            ['chats.tg_chat_id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'players_chats',
        sa.Column('tg_user_id', sa.Integer(), nullable=False),
        sa.Column('tg_chat_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['tg_chat_id'],
            ['chats.tg_chat_id'],
        ),
        sa.ForeignKeyConstraint(
            ['tg_user_id'],
            ['players.tg_user_id'],
        ),
    )
    op.create_table(
        'players_games',
        sa.Column('tg_user_id', sa.Integer(), nullable=False),
        sa.Column('game_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['game_id'],
            ['games.id'],
        ),
        sa.ForeignKeyConstraint(
            ['tg_user_id'],
            ['players.tg_user_id'],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players_games')
    op.drop_table('players_chats')
    op.drop_table('games')
    op.drop_table('players')
    op.drop_table('chats')
    # ### end Alembic commands ###
